export const MOBILE_BREAKPOINT = 760;
export const SMALLER_MOBILE_BREAKPOINT = 385;
export const MOBILE_BREAKPOINT_MAX_WIDTH = `(max-width:${MOBILE_BREAKPOINT}px)`;
export const SMALLER_MOBILE_BREAKPOINT_MAX_WIDTH = `(max-width:${SMALLER_MOBILE_BREAKPOINT}px)`;
export const MOBILE_BREAKPOINT_MIN_WIDTH = `(min-width:${MOBILE_BREAKPOINT}px)`;
